hotels:
- name: Dhigali Maldives
- name: Cora Cora Maldives
- name: Hideaway Beach Resort & Spa
- name: Lily Beach Resort & Spa

trip:
check_in: "2027-04-03"
check_out: "2027-04-11"
guests: 4
  - age: 8
  - age: 9
meal_plan: "All Inclusive"

room:
  strategy: "cheapest_available_for_4_guests"
  max_occupacy: 4
  Preferred: "lowest price"

price:
  type: "Accomodation package"
  includes:
    - "Accomodation"
    - "All Inclusive"
  excludes:
    - "Fligths"

alerts:
any_price_drop: true
drop_percent: 8
price_below_huf: 2300000

schedule:
checks_per_day: 3
timezone: "Europe/Budapest"
